Analyze a real phishing example
sanesecurityonline/sanesecurityonline pull request #12
Opened 2018-02-27 21:42 UTC by kunev

2018-02-28 09:07 UTC, AndrewRadev requested changes
Като цяло изглежда добре, само трябва да се фикснат няколко typo-та. 

Бих го разгледал рендериран, за да преценя как изглеждат картинките. На гледане в github, първата ми изглежда твърде голяма, много whitespace, втората ми изглежда с твърде дребен шрифт. Ако пробваш да screenshot-неш с оразмерени прозорци/zoom-нат шрифт, може би ще е по-добре ratio-то информация/шум.

2018-02-28 09:07 UTC, AndrewRadev commented on content/posts/a-phishing-example.md
> +детайли. Това е един от най-добрите начини да се предпазим от негативните
"Двуфакторното"

2018-02-28 09:07 UTC, AndrewRadev commented on content/posts/a-phishing-example.md
> +title: "Един phishing пример от близо"
"от близо" -> "отблизо"

2018-02-28 12:27 UTC, kunev commented
Оразмеряването на скрийншотите звучи като да има хляб в него. Ще го пробвам по-късно днес.

2018-03-05 11:36 UTC, kunev commented
Пооправих размера на screenshot-ите. Понеже се оказа, че адреса, от който сервират се променя, добавих и малко общо обяснение за own-ването на CMS-и.

2018-03-05 11:46 UTC, AndrewRadev approved these changes

2018-03-05 11:48 UTC, AndrewRadev commented
Изглежда ми мърджабилно. :+1: 

Секцията за CMS обаче ми изглежда вербозна, не съм сигурен доколко би им пукало на хората за това как точно си сменят адреса. Бих сложил нещо като "докато писахме статията адреса се промени, така че адреса, който видите, може да не е същия, но вероятно ще споделя същите характеристики". 

Алтернативно, даже може да не се обясни. Не би трябвало да кликат на въпросния линк така или иначе.

2018-03-05 12:21 UTC, kunev commented
Отделна "fun facts" секция? 😄 Или може би просто нещо оградено с `hr`-та? Според мен има стойност в това да знаеш повърхностно как работи атаката, но съм съгласен, че въвеждането на CMS като понятие може би не носи много полза.

2018-03-05 13:06 UTC, AndrewRadev commented
Long-term за такива неща наистина би имало малки статийки с обяснения "цъкнете тук, за да разберете това нещо". В случая, ако все пак искаш да обясниш това, може да го маркираш в *italics*, и да го посъкратиш малко. Но аз по-скоро бих го дропнал изцяло, понеже (доколкото аз разбирам) се свежда до "ако някой хване лошите, те се местят", което не виждам много стойност в това да се казва, особено с толкова много думи.

2018-03-06 18:27 UTC, kunev commented
Fair point.

2018-03-06 18:28 UTC, merged