Two factor authentication
sanesecurityonline/sanesecurityonline pull request #16
Opened 2018-04-03 19:30 UTC by AndrewRadev

Както съм написал в началото, термина на български може да е:

- Двуфакторна автентикация
- Двуфакторно удостоверяване
- Двуфакторна идентификация

Второто се ползва от фейсбук и май го видях най-често на първата страница на резултатите в google. Но не съм сигурен, че има голямо значение. Бих използвал *един* превод и останалите съм ги отбелязал. Ако има предпочитание към един конкретен, ще пренапиша статията да ползвам него.

2018-04-10 06:19 UTC, kunev requested changes
Оставил съм няколко inline коментари, предимно прозаизми.

Отделно, има два линка към phishing статията и два към threat modeling. Нямам много силно мнение по въпроса, но ми се струва, че няма смисъл да са по повече от един. Ако се сещаш за лесен начин да смачкаш отделните парчета от текста така, че да останат с по един ref към всяко ми се струва, че би било по-хубаво. Ако не е тривиално обаче, няма смисъл да се хàбиш.

2018-04-10 06:19 UTC, kunev commented on content/posts/two-factor-authentication.md
> +Термина "двуфакторна автентикация" ("two-factor authentication") често се съкращава до "2FA". Това описва широк набор от начини за допълнително подсигуряване на акаунта ви в някакъв сайт. Някъде може
s/някакъв сайт/някои сайтове/

2018-04-10 06:19 UTC, kunev commented on content/posts/two-factor-authentication.md
> +Обикновено, сайтовете изискват потребителско име или мейл адрес и парола. Ако сайта поддържа 2FA, може *освен* тези идентификатори да се изисква нещо допълнително. Това означава, че дори някой да се
По-скоро „това няма да е достатъчно“, от колкото „няма да може“. Доста е subtle като разлика, но е доста по-малко вероятно да се интерпретира грешно.

2018-04-10 06:19 UTC, kunev commented on content/posts/two-factor-authentication.md
> +Автентикацията, която използва два **различни** фактора, е доста по-сигурна, понеже има два напълно различни метода за разбиването ѝ. Ако за онлайн банкиране има нужда от парола и от токен устройство
„има два напълно различни метода“ звучи малко като да имаш опция от поне два отделни вектора, които можеш да експлойтваш. По-добре би било нещо от типа на „изисква успех в две напълно отделни атаки“.

2018-04-10 06:19 UTC, kunev commented on content/posts/two-factor-authentication.md
> +Важно е обаче факторите да са различни. Ако имате парола и физическо устройство, и си запишете паролата на бележка, която оставите *до* устройството, това свежда и двете неща до "нещо, което притежав
s/Така/Това/

2018-04-10 07:04 UTC, AndrewRadev commented
Поправките изглеждат смислени, ще ги мина може би днес. Ще видя и за чифтовете линкове, и аз забелязах поне едното повторение, и не ми се щеше да го има.

2018-04-10 19:20 UTC, AndrewRadev commented
Направих промените, и tweak-нах още едно-две неща, които ми звучаха по-тежко. Хвърли ѝ още един прочит.

2018-04-15 08:20 UTC, kunev approved these changes

2018-04-15 08:20 UTC, kunev commented on content/posts/two-factor-authentication.md
> +Автентикацията, която използва два **различни** фактора, е доста по-сигурна, понеже изисква успех в две напълно отделни атаки за да бъде разбита. Ако за онлайн банкиране има нужда от парола и от токе
запетайка пред „за да“

2018-04-15 08:20 UTC, kunev commented on content/posts/two-factor-authentication.md
> +Важно е обаче факторите да са различни. Ако имате парола и физическо устройство, и си запишете паролата на бележка, която оставите *до* устройството, това свежда и двете неща до "нещо, което притежав
Не се споменава никъде за банки, а на края имат достъп до финанси. Може би по-добре просто в началото на примера да се казва, че иде реч за достъп до банка.

2018-04-15 08:20 UTC, kunev commented on content/posts/two-factor-authentication.md
> +Банките редовно използват "токен устройства". Това, което се ползва от ПИБ, например, изглежда така:
Може ли да е „това, което ползват някои банки“? Разбирам ценността на съвсем конкретните примери, ама споменаването на конкретни банки ми е two parts (pun not entirely intended).

2018-04-15 08:51 UTC, AndrewRadev commented on content/posts/two-factor-authentication.md
> +Важно е обаче факторите да са различни. Ако имате парола и физическо устройство, и си запишете паролата на бележка, която оставите *до* устройството, това свежда и двете неща до "нещо, което притежав
Хм, исках да продължа с примера от горния параграф, но наистина не е много ясно. Опитах се да го уточня. Ще го донатаманяваме в master, ако не стига.

2018-04-15 08:54 UTC, AndrewRadev commented on content/posts/two-factor-authentication.md
> +Банките редовно използват "токен устройства". Това, което се ползва от ПИБ, например, изглежда така:
Да, чудех се за това. Ще ми се да имаме няколко примера/снимки, но с това имам опит аз. Уникредит имат тотално различна схема с app (която според мен е ненужно сложна, но това е друга тема).

Ще го направя generic, пък може би някой светъл ден някой contributor ще добави инфо и за други банки.

2018-04-15 09:01 UTC, merged